---
kind: "pipeline"
name: "demo"

steps:
  - name: "test"
    image: "debian:stretch-slim"
    commands:
      - echo "Hello!"

trigger:
  branch:
    - master

---
kind: "pipeline"
name: "deloyment-demo"

steps:
  - name: "dep"
    image: "debian:stretch-clim"
    commands:
      - echo "Hi!"

trigger:
  event:
    - "success"
    - "promote"

depends_on:
  - "demo"
