---
kind: "pipeline"
name: "demo"

steps:
  - name: "lint"
    image: "quay.io/littlemanco/lint:1.0.2"
    commands:
      - arc lint --ansi --rev=refs/remotes/origin/${DRONE_TARGET_BRANCH}

trigger:
  event:
    - pull_request

node:
  co.littleman.k8s.tolerates: fault-tolerant